name: Native validation
on:
  push:
    branches: [main]
  pull_request:
jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        runner: [gcoms-linux-x64, gcoms-windows-x64]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: https://code.forgejo.org/actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false
      - run: python3 scripts/ci.py
        env:
          CARGO_BUILD_JOBS: '2'
