// Generated by gc-rpc-types. Do not edit.
export type OperationId = string;
export type DecimalU64 = string;
export type MethodKind = "query" | "operation" | "session";
export type ErrorCode = "invalid_request" | "version" | "instance" | "service" | "method" | "unauthorized" | "conflict" | "expired" | "unavailable" | "busy" | "payload_too_large" | "storage" | "transport" | "timeout" | "protocol";
export type RpcError = { code: ErrorCode, message: string, };
export type OperationToken = { id: OperationId, deadline: DecimalU64, };
export type OperationHandle = { destination: string, instance: string, service: string, version: number, method: string, operation: OperationToken, };
export type Invocation = { "action": "call", args: unknown, operation: OperationToken | null, } | { "action": "status", operation_id: OperationId, };
export type Request = { rpc: number, id: OperationId, instance: string, service: string, version: number, method: string, invocation: Invocation, };
export type Outcome = { "kind": "ok", "value": unknown } | { "kind": "error", "value": unknown };
export type ReplyBody = { "state": "done", outcome: Outcome, } | { "state": "running" } | { "state": "outcome_unknown" } | { "state": "unavailable" } | { "state": "failed", error: RpcError, };
export type Reply = { rpc: number, id: OperationId, instance: string, service: string, version: number, method: string, body: ReplyBody, };
