import { output, validators } from '@gcoms/rpc-codegen';
import { readFileSync } from 'node:fs';
const root = new URL('../', import.meta.url);
  const wire = JSON.parse(readFileSync(new URL('schemas/wire.json', root), 'utf8'));
  output(new URL('src/wire.ts', root), '// Generated by gc-rpc-types. Do not edit.\n' + wire.typescript);
  output(new URL('src/validators.js', root), validators({ validRequest: wire.request, validReply: wire.reply, validHandle: wire.handle }));
